config/routes.rb
Retrack::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  resources :microposts do
    member do
      post :retweet
    end
  end

  match '/profile', :to => 'pages#user_home'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  get "pages/user_home"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/main"

  

   root :to => 'pages#main'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  has_many :microposts, :dependent => :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                    class_name: "Relationship",
                                    dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :retweets, :through => :microposts
  
  scope :admin, where(admin: true)
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :email, :presence => true,
                   :format => { :with => email_regex },
                   :uniqueness => { :case_sensitive => false }
                   
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }
  
  before_save :encrypt_password
  
  def has_password? (submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def following? (other_user)
    relationships.find_by_followed_id(other_user.id)
  end
  
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end
  
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
  
  
  private
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :edit, :update, :destroy, :following, :followers]
  before_filter :authenticate, :only => [:index, :edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy

  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page], :per_page => 25)
  end
  
  def new
    @title = "Sign up"
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        sign_in @user
      format.html { redirect_to @user , notice: "Your account was succesfully created! Welcome to Retracks"  }
      format.json { render :json => @user, :status => :created, :location => @user }
      else
        @title = "Sign up"
        format.html { render :new }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name
    @micropost = Micropost.new if signed_in?
  end
  
  def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
    
  private
  
    # def authenticate
    #   deny_access unless signed_in?
    # end
    # 
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50})
      gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                              :class => 'gravatar',
                                              :gravatar => options)
    end
    # Returns the Gravatar (http://gravatar.com/) for the given user.
  # def gravatar_for(user)
  #     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #     gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
  #     image_tag(gravatar_url, alt: user.name, class: "gravatar")
  #   end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
	<div><%= f.hidden_field :followed_id %></div>
	<%= f.submit "Follow", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user)%>
	<div id="follow_form">
		<% if current_user.following?(@user)%>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
			 html: { method: :delete }, remote: true) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
  | <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<div class="span12" id="innerform" align="center">
	<h2>Edit Your Profile</h2><br />
	<fieldset>
		<legend></legend>
			<%= simple_form_for @user, :html => {:novalidate => true, :class => 'form-horizontal'} do |f|%>
				<%= f.input :name, :placeholder => 'ex: John Doe'%>
				<%= f.input :email , :placeholder => 'ex: example@email.com'%>
				<%= f.input :password %>
				<%= f.input :password_confirmation %><br />
				<div>
				  <%= gravatar_for @user %>
				  <a href="http://gravatar.com/emails">change</a>
				</div>
				<div class="form-actions">
					<%= f.submit "Save", :class => 'btn btn-primary' %>
				</div>
			<% end %>
			
	</fieldset>
</div>

app/views/users/home_user.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>

app/views/users/index.html.erb
<h1 align="center">All users</h1><br />
<div style="display: block; margin: 0 auto; width: 100%;">
<div class="row-fluid" style="margin: 0 auto;">
	<div class="apple_pagination" style="margin: 0 auto;">
	<%= will_paginate @users, :container => false %>
	</div>
	<div style="background: grey ; margin: 0 auto; width: 60%;">
	
			<ul class="users" style="width: 400px; background: white;" >
				<% @users.each do |user| %>
					<li style="border-bottom: 1px solid black; margin: 0 auto;">
						<%= render user %><br />
					</li>
				<% end %>
			</ul>
	</div>
	<div class="apple_pagination" style="margin: 0 auto;">
	<%= will_paginate @users, :container => false %>
	</div>
</div>
</div>

app/views/users/new.html.erb
<div class="span12" id="innerform" align="center">
	<h2>Sign up</h2><br />
	<fieldset>
		<legend></legend>
			<%= simple_form_for @user, :html => {:novalidate => true, :class => 'form-horizontal'} do |f|%>
				<%= f.input :name, :placeholder => 'ex: John Doe'%>
				<%= f.input :email , :placeholder => 'ex: example@email.com'%>
				<%= f.input :password %>
				<%= f.input :password_confirmation %><br />
				<div class="form-actions">
					<%= f.submit "Sign Up", :class => 'btn btn-primary' %>
				</div>
			<% end %>
	</fieldset>
</div>

app/views/users/show.html.erb
<div  style="margin: 0 auto; width: 960px;">
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<% if signed_in? && current_user.name == @user.name%>
			  <table class="front" summary="For signed-in users">
			    <tr>
			      <td class="main">
					<h3>Home &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| Your posts and retracks.</h3><br/<br/>
			        <h1 class="micropost">Share a Track:</h1>
			        <%= render 'shared/micropost_form' %>
			      </td>
			    </tr>
			  </table>
			<% end %>
			
			<% unless @user.microposts.empty?%>
				<table class="microposts" summary="User microposts">
					<%= render @microposts %>
				</table>
					<div class="apple_pagination" style="margin: 0 auto; width:100%;">
					<%= will_paginate @microposts, :container => false%>
					</div>
			<% end %>
		</td>
		
		<td style="background: orange; vertical-align: top; padding: 10px;margin: 0 auto;">
			<ol style="background: white; padding-left: 10px;padding-top: 20px;margin: 0 auto; padding-bottom: 10px;">
			<span>
			<h2 class="picpic" style="font-size: 18px;">
				<%= gravatar_for @user%>
				<%= @user.name %>
			</h2>
			</span>
			<span>
			
			<strong>Name</strong> <%= @user.name %><br />
			<strong>URL</strong> <%= link_to user_path(@user), @user%><br />
			<strong>Email</strong> <%= @user.email %>
			<section>
				<br/>
		        <%= render 'shared/stats' %><br/>
				<%= render 'follow_form' if signed_in? %>
		      </section>
				
			</span>
				</ol>
		</td>
	</tr>
</table>
</div>

app/views/users/show_follow.html.erb
<%= provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate @users %>
    <% end %>
  </div>
</div>