config/routes.rb
Retrack::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  resources :microposts do
    member do
      post :retweet
    end
  end

  match '/profile', :to => 'pages#user_home'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  get "pages/user_home"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/main"

  

   root :to => 'pages#main'

end

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <!-- <ol class="microposts"> -->
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  <!-- </ol> -->
  <!-- <%= will_paginate @feed_items %> -->
<% end %>

app/views/shared/_feed_item.html.erb
<!-- <li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="name"><%= feed_item.name %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method:  :delete,
                                     confirm: "You sure?",
                                     title:   feed_item.name %>
  <% end %>

</li> -->

<tr>
  <td class="micropost" align="center">
	<div class="row-fluid" style="border: 0px solid grey; width: 600px;">
	<div class="span1" style="width: 50px; height: 60px; margin-right: 0;padding-top: 5px; padding-left: 3px;"><%= link_to gravatar_for(feed_item.user), feed_item.user %></div>
	<div class="span6" style="width: 450px;" align="left">
    <span class="content"><strong> <%= link_to feed_item.user.name, feed_item.user %> <br/><%= feed_item.name %></strong></span><br />
	<span class="content">Open with:
		<% if feed_item.name.include? '#mixtape'%>
			<% bad = "#mixtape"%>
			<% feed_item.name = (feed_item.name.split(' ') - bad.split(' ')).join(' ') %>
			<%= link_to( image_tag("Datpiff-Logo-2.png", :size => "20x20"), "http://www.datpiff.com/mixtapes-search.php?criteria=#{feed_item.name}")%>
		<% elsif feed_item.name.include? '#spotify'%>
			<% bad = "#spotify"%>
			<% feed_item.name = (feed_item.name.split(' ') - bad.split(' ')).join(' ') %>
			<%= link_to( image_tag("spotify_logo.png", :size => "20x20"), "spotify:search:#{feed_item.name}")%>
		<% elsif feed_item.name.include? '#soundcloud'%>
			<% bad = "#soundcloud"%>
			<% feed_item.name = (feed_item.name.split(' ') - bad.split(' ')).join(' ') %>
			<%= link_to( image_tag("soundcloud-logo.png", :size => "20x20"), "http://soundcloud.com/search?q%5Bfulltext%5D=#{feed_item.name}")%>
		<% elsif feed_item.name.include? '#grooveshark'%>
			<% bad = "#grooveshark"%>
			<% feed_item.name = (feed_item.name.split(' ') - bad.split(' ')).join(' ') %>
			<%= link_to( image_tag("Grooveshark_Logo.png", :size => "20x20"), "http://grooveshark.com/#!/search?q=#{feed_item.name}")%>
		<% elsif feed_item.name.include? '#hulkshare'%>
			<% bad = "#hulkshare"%>
			<% feed_item.name = (feed_item.name.split(' ') - bad.split(' ')).join(' ') %>
			<%= link_to( image_tag("hulkshare.gif", :size => "20x20"), "http://www.hulkshare.com/search.php?q=#{feed_item.name}")%>
		<% elsif feed_item.name.include? '#youtube'%>
			<% bad = "#youtube"%>
			<% feed_item.name = (feed_item.name.split(' ') - bad.split(' ')).join(' ') %>
			<%= link_to( image_tag("youtube.jpg", :size => "20x20"), "http://www.youtube.com/results?search_query=#{feed_item.name}")%>

	   <% elsif%>
	
			<%= link_to( image_tag("spotify_logo.png", :size => "20x20"), "spotify:search:{#{feed_item.name}}")%>
			<!-- <%= link_to( image_tag("itunes_logo.jpg", :size => "20x20"), "")%> -->
			<%= link_to( image_tag("lastfm_logo.png", :size => "20x20"), "http://www.last.fm/search?q=#{feed_item.name}&type=track")%>
			<%= link_to( image_tag("soundcloud-logo.png", :size => "20x20"), "http://soundcloud.com/search?q%5Bfulltext%5D=#{feed_item.name}")%>
			<%= link_to( image_tag("Grooveshark_Logo.png", :size => "20x20"), "http://grooveshaerk.com/#!/search?q=#{feed_item.name}")%>	
			<%= link_to( image_tag("youtube.jpg", :size => "20x20"), "http://www.youtube.com/results?search_query=#{feed_item.name}")%>
	<% end %>
	<% unless feed_item.link_url.blank?%>
	 <p>Link:<%= link_to feed_item.link_url, feed_item.link_url%></p>
	<% else %>
	<% end%>
	



	
	</span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
	<span class="Retrack" style="color: green; font-size: 13px;">
		<% if feed_item.user != current_user %>
			<%= link_to image_tag("retrack-action.png", :size => "20x20"), retweet_micropost_path(feed_item), :method => :post %>
			<strong><%= link_to "Retrack", retweet_micropost_path(feed_item), :method => :post , :style => "color: green;"%></strong>
		<% end %>
	</span>
	</div>
	<div class="span1" style="padding-top: 20px;">
	
	 <% if current_user?(feed_item.user) %>
 	   <%= link_to "delete", feed_item, method:  :delete,
 	                                    confirm: "You sure?",
 	                                    title:   feed_item.name %>
 	 <% end %>
	</div>
	</div><br/>
  </td>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <div class="field">
    <%= f.text_field :name %>
  </div>
<div class="field">
	<%= f.label "Link"%> <%= f.text_field :link_url, :placeholder => "(optional)" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats" style="font-size: 20px;">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a><br/>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a><br/>
  <a href="<%= current_user %>">
    <strong id="track_retracked" class="stat">
      <%= @user.microposts.count %>
    </strong>
    Tracks
  </a>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>