config/routes.rb
Retrack::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  resources :microposts do
    member do
      post :retweet
    end
  end

  match '/profile', :to => 'pages#user_home'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  get "pages/user_home"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/main"

  

   root :to => 'pages#main'

end

app/views/pages/_form.html.erb
<%= form_for @micropost, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Post a track", :class => 'control-label' %>
    <div class="controls">
		<%= f.text_field :name, :class => 'text_field input-xlarge', :placeholder => "Your song title - Artists" %>
		<%= f.submit "Share", :class => 'btn btn-primary' %>	
    </div>
  </div>
  <div class="control-group">
    <!-- <%= f.label :link, :class => 'control-label' %> -->
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field', :placeholder => "Add a link (optional)" %>
    </div>
  </div>

<% end %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="span8">	
	<!-- <div class="row-fluid" id="BannerBackground" align="center">
			 <%= image_tag "banner_example.png"%>
	</div> -->
	<div class="page-header">
		<h2>Share your favorite tracks</h2>
	</div>
	<div class="alert alert-info">
		<div class="row-fluid" id="PostingSession">
			<%= render 'form', :locals => { :micropost => @micropost } %>
		</div>
	</div>
	<div class="row-fluid" id="AllPosts">
		<div class="row">
			<table class="table table-striped">
			<% @microposts.each do |micropost| %>
				<tr>
						<div class="span6">
							<td><%= link_to micropost.id, micropost_path(micropost) %></td>
							<td><%= micropost.name %></td>
							<td><%= time_ago_in_words(micropost.created_at) %> ago</td>
						</div>
						<div class="span6">
							<!-- Add Regex to detect Artist part and Song part for Spotify-->
							<td><%= micropost.spotify.blank? ? '--' : "spotify:search:track:#{micropost.spotify}" %></td>
							<!-- Add Regex to detext Artist part and song part for Itunes-->
						    <td><%= micropost.itunes.blank? ? '--' : "none", "http://itunes.com/album/song"""%></td>
						    <td><%= link_to micropost.link.blank? ? 'none' : micropost.link%>, micropost.link</td>
						</div>
				</tr>
	  		<% end %>
			</table>
		</div>
	</div>
</div>

<div class="span4">
	<!-- <div class="hero-unit"> -->
		<div class="profile-top">
			<div class="profile-pic">
				<img src="" width="50" height="50" />
			</div>
			<div class="profile-name">
				<p>Username<p>
				<p>Full Name</p>
			</div>
		</div>
		<div class="profile-bottom">
			<div class="profile-description">
				<p>about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus et mi imperdiet tempor. Aliquam urna libero, bibendum sed volutpat.</p>
			</div>
			<div class="profile-website" align="center">
				<input class="btn btn-mini" type="button" value="website">
			</div>
		</div>
  	<!-- </div> -->
</div>

app/views/pages/main.html.erb
  <div class="span12" id="homepage" align="center">
  	<div class="hero-unit" style="height: 600px; padding-left: 0px; padding-right: 0; padding-top: 10px;">
	  <span>
		 <%= image_tag "retrackHow.png", :width => "100%" %>
	  </span>
	  <h2>Love, Share and Retrack</h2>
	  <p>Retrack is currently in beta</p>
	<% if signed_in? %>
		<%= link_to "Go back to my profile", current_user,  :class=>"btn btn-primary btn-large" %>
	<% else %>
	  <p>
		<%= link_to "Log in", signin_path,  :class=>"btn btn-primary btn-large" %>
	    <%= link_to "Sign Up", new_user_path, :class => "btn btn-primary btn-large" %>
	  </p><br/>
	<% end %>
	</div>
	
		 
  </div>

app/views/pages/user_home.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">

			  <table class="front" summary="For signed-in users">
			    <tr>
			      <td class="main">
					<div id="span8">
					<h3>Feed &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| Posts from all the users you follow.</h3>
				 	<%= render 'shared/feed' %>
					</div>
			      </td>
			    </tr>
			  </table>
			  <div class="apple_pagination" style="margin: 0 auto; width:100%;">
			  <%= will_paginate @feed_items, :container => false %>
			  <div>
			

		</td>
		<td style="background: orange; vertical-align: top; padding: 10px;">
			<ol style="background: white; padding-left: 10px;padding-top: 20px;margin: 0 auto; padding-bottom: 10px;">
			<span>
			<h2 class="picpic" style="font-size: 18px;">
				<%= gravatar_for current_user%>
				<%= current_user.name %>
			</h2>
			</span>
			<span>
				
			<strong>Name</strong> <%= current_user.name %><br />
			<strong>URL</strong> <%= link_to user_path(current_user), current_user%><br />
			<strong>Email</strong> <%= current_user.email %>
			<section>
				<br/>
		        <%= render 'shared/stats' %><br/>
		      </section>
			</span>
			</ol>
		</td>
	</tr>
</table>