config/routes.rb
Retrack::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  resources :microposts do
    member do
      post :retweet
    end
  end

  match '/profile', :to => 'pages#user_home'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  get "pages/user_home"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/main"

  

   root :to => 'pages#main'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Retrack | <%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
	<div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
			  <%= link_to image_tag("Logo.png", :width => "100px"), root_path ,:class => "brand"%>
			<ul class="nav">
			  <li class="active">
			    <a href="#">Discover</a>
			  </li>
			<% if signed_in? %>
			<li><%= link_to "Home", current_user%></li>
			<li><%= link_to "Profile", profile_path%></li>
			<li><%= link_to "Users", users_path%></li>
			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
			<% else%>
				<li class="right"><%= link_to "Sign in", signin_path %></li>
			<% end %>
			</ul>
	    </div>
	  </div>
	</div>
	<div class="row-fluid">
		<div class="container">
			<%  flash.each do |name, msg|%>
			<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
				<%= msg %>
			</div>
			<% end %>
		</div>
		<%= yield %>

	</div>
</div>


</body>
</html>